/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        darkBg: "#0B0F19",
        glassBg: "var(--glass-bg)",
        glassBorder: "var(--glass-border)",
        brandBlue: "var(--accent-blue)",
        brandGreen: "var(--accent-emerald)",
        brandPurple: "var(--accent-purple)",
        "surface-variant": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "secondary": "#4059aa",
        "on-tertiary-container": "#4600a7",
        "tertiary-fixed-dim": "#d0bcff",
        "on-surface": "#191c1e",
        "on-primary-container": "#00422b",
        "primary-container": "#10b981",
        "inverse-primary": "#4edea3",
        "on-secondary": "#ffffff",
        "primary-fixed": "#6ffbbe",
        "primary": "#006c49",
        "outline": "#6c7a71",
        "secondary-fixed": "#dce1ff",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "on-surface-variant": "#3c4a42",
        "secondary-fixed-dim": "#b6c4ff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#264191",
        "error": "#ba1a1a",
        "surface-container-high": "#e6e8ea",
        "on-error-container": "#93000a",
        "tertiary": "#6d3bd7",
        "on-tertiary-fixed-variant": "#5516be",
        "on-primary-fixed": "#002113",
        "on-tertiary-fixed": "#23005c",
        "on-tertiary": "#ffffff",
        "outline-variant": "#bbcabf",
        "inverse-on-surface": "#eff1f3",
        "inverse-surface": "#2d3133",
        "surface-container-highest": "#e0e3e5",
        "surface-container": "#eceef0",
        "on-secondary-container": "#1d3989",
        "on-primary-fixed-variant": "#005236",
        "primary-fixed-dim": "#4edea3",
        "background": "#f7f9fb",
        "surface-tint": "#006c49",
        "on-primary": "#ffffff",
        "on-background": "#191c1e",
        "secondary-container": "#8fa7fe",
        "surface": "#f7f9fb",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#00164e",
        "tertiary-fixed": "#e9ddff",
        "tertiary-container": "#b090ff",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1440px",
        "md": "16px",
        "gutter": "24px",
        "xl": "32px",
        "unit": "8px",
        "xxl": "48px",
        "lg": "24px",
        "xs": "4px",
        "sm": "8px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "mono-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "mono-sm": ["13px", {"lineHeight": "18px", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [],
}
